### ISSUE TITLE
"delete all" causes application crash

### ISSUE THREAD

**Issue by fschrofner** [AlexKang/loopboard#6]
The Sample.stop() method causes the application to crash on my device (HTC One, Android 5.0.2).

Logcat:

```
02-06 19:49:49.248  15462-15462/com.alexkang.loopboard D/MainActivity﹕ stop all called!
02-06 19:49:49.248  15462-15462/com.alexkang.loopboard D/MainActivity﹕ trying to stop: Sample 0
02-06 19:49:49.249  15462-15462/com.alexkang.loopboard D/Sample﹕ !isImported && audioTrack != null
02-06 19:49:49.249  15462-15462/com.alexkang.loopboard A/AudioTrackShared﹕ static flush
02-06 19:49:49.249  15462-15462/com.alexkang.loopboard A/libc﹕ Fatal signal 6 (SIGABRT), code -6 in tid 15462 (xkang.loopboard)
```

I've added some logs, since you didn't use any. This should guide us into the right direction..

**Comment by FlorianSchrofner** [comment]
It's caused by `audioTrack.flush()`, if I remove that line it works fine..

**Comment by AlexKang** [comment]
Ok I did an overhaul of the app, including the media playback. Reopen this if the issue is still there.
