### ISSUE TITLE
[Clarification request] How to use sounds from internal storage ?

### ISSUE THREAD

**Issue by Wikinaut** [AlexKang/loopboard#9]
"Currently, the application can record sounds through the microphone (or use sounds from internal storage!)" -- but how ?

**Comment by AlexKang** [comment]
Oh if there are audio files in the "LoopBoard" folder (.mp3, .wav, .mp4, .m4a), then the app should be able to load them.

I haven't worked on this app for a long time, but I will go through and clean it up at some point this year.

**Comment by Wikinaut** [comment]
You did not mention previously, that the audio files have to "live" in the LoopBoard folder, I will try it and report here.
